What is a 1D Array?

A 1D (One-Dimensional) Array is a single "line" of data. In Python, you might know it as a List, but in NumPy, it's called a Vector.

The Structure: It only moves in one direction (left to right).

The Rule: Every item inside must be the same "type" (e.g., all integers or all strings).



Real-World Example

Imagine you are tracking the temperature every hour for 5 hours.
Your data would look like this: [30, 32, 31, 29, 30]

How to explain the "Big 5" for a 1D Array:

If we have: arr = np.array([10, 20, 30, 40])

ndim (Dimensions): It will be 1. Because there is only one axis (the horizontal axis).

shape: It will be (4,). This tells you there are 4 elements in one row. (The comma is just NumPy's way of saying there is no second dimension).

size: It will be 4. Total number of items.

dtype: It will be int64. Since they are whole numbers.

type(): It will be numpy.ndarray. (This is the "class" name for all NumPy arrays).

Why is 1D important for Data Engineering?

In a database, a single column (like "Customer_Age" or "Price") is essentially a 1D array. When you pull one column from a SQL table to do math on it, you are working with a 1D structure.

In [9]:
import numpy as np

temp_array = np.array([30,32,31,29,30])
print(temp_array)
print(f"Diamension Of Array: {temp_array.ndim}")
print(f"Total Elements (size): {temp_array.size}")
print(f"Total Elements (shape): {temp_array.shape}")
print(f"Total Elements (datatype): {temp_array.dtype}")


[30 32 31 29 30]
Diamension Of Array: 1
Total Elements (size): 5
Total Elements (shape): (5,)
Total Elements (datatype): int64


In [ ]:
A 2D Array is where things get interesting for a Data Engineer. If a 1D array is a "line," a 2D array is a "Table."

What is a 2D Array?

A 2D (Two-Dimensional) Array is data arranged in Rows and Columns. In the world of Data Science and Engineering, this is often called a Matrix.

The Structure: It moves in two directions: Horizontal (Rows) and Vertical (Columns).

The Look: It looks like a nested list: [[row1], [row2]].


Real-World Example

Think of a Student Marksheet.

Rows: Different students (Student A, Student B).

Columns: Different subjects (Math, Science, English).

Math	Science	English
Student 1	80	85	90
Student 2	75	80	85


How to explain the "Big 5" for a 2D Array:

If we have: arr2d = np.array([[80, 85, 90], [75, 80, 85]])

ndim (Dimensions): It will be 2. Because it has two axes (Height and Width).

shape: It will be (2, 3). This means 2 rows and 3 columns. (Always Rows first, then Columns).

size: It will be 6. (Total number of cells: 2 * 3 = 6).

dtype: Usually int64 or float64.

type(): Still numpy.ndarray.


Why is 2D the "King" of Data Engineering?

Almost everything you did in MySQL or MongoDB translates to a 2D array. When you load a CSV file or a SQL table into your Python code using a library like Pandas, it treats that data as a 2D structure.

If you understand 2D arrays, you understand how data is stored in 90% of the world's databases!

In [16]:
import numpy as np

arr2d = np.array([
    [80,85,90],
    [75,80,85]])

print(arr2d)
print(f"The Shape Of Array :- {arr2d.shape}")
print(f"The Size Of Array :- {arr2d.size}")
print(f"The Datatype Of An Array :- {arr2d.dtype}")
print(f"The Diamension Of An Array :- {arr2d.ndim}")

[[80 85 90]
 [75 80 85]]
The Shape Of Array :- (2, 3)
The Size Of Array :- 6
The Datatype Of An Array :- int64
The Diamension Of An Array :- 2


In [ ]:
## Practise Questions For 1D And 2D

Question 1: The Inventory (1D)

You are tracking the stock of 5 different items in a warehouse. You create this array:
stock = np.array([150, 200, 50, 0, 300])

A) What is the ndim of this array?

B) What is the shape?


Question 2: The Sales Table (2D)

You have a table showing sales for 3 different stores over 4 days.
sales = np.array([[10, 12, 11, 15], [20, 22, 21, 25], [5, 8, 7, 9]])

A) How many Rows and Columns does this array have? (Answer in shape format).

B) What is the size of this array?




Question 3: The Reshape Puzzle

You have a 1D array with 12 elements: data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

You want to turn this into a 2D Table for a report. Which of these reshape commands will WORK and which will FAIL?

data.reshape(3, 4)

data.reshape(2, 5)

data.reshape(6, 2)