What is a 1D Array?

A 1D (One-Dimensional) Array is a single "line" of data. In Python, you might know it as a List, but in NumPy, it's called a Vector.

The Structure: It only moves in one direction (left to right).

The Rule: Every item inside must be the same "type" (e.g., all integers or all strings).



Real-World Example

Imagine you are tracking the temperature every hour for 5 hours.
Your data would look like this: [30, 32, 31, 29, 30]

How to explain the "Big 5" for a 1D Array:

If we have: arr = np.array([10, 20, 30, 40])

ndim (Dimensions): It will be 1. Because there is only one axis (the horizontal axis).

shape: It will be (4,). This tells you there are 4 elements in one row. (The comma is just NumPy's way of saying there is no second dimension).

size: It will be 4. Total number of items.

dtype: It will be int64. Since they are whole numbers.

type(): It will be numpy.ndarray. (This is the "class" name for all NumPy arrays).

Why is 1D important for Data Engineering?

In a database, a single column (like "Customer_Age" or "Price") is essentially a 1D array. When you pull one column from a SQL table to do math on it, you are working with a 1D structure.

In [9]:
import numpy as np

temp_array = np.array([30,32,31,29,30])
print(temp_array)
print(f"Diamension Of Array: {temp_array.ndim}")
print(f"Total Elements (size): {temp_array.size}")
print(f"Total Elements (shape): {temp_array.shape}")
print(f"Total Elements (datatype): {temp_array.dtype}")


[30 32 31 29 30]
Diamension Of Array: 1
Total Elements (size): 5
Total Elements (shape): (5,)
Total Elements (datatype): int64


In [ ]:
A 2D Array is where things get interesting for a Data Engineer. If a 1D array is a "line," a 2D array is a "Table."

What is a 2D Array?

A 2D (Two-Dimensional) Array is data arranged in Rows and Columns. In the world of Data Science and Engineering, this is often called a Matrix.

The Structure: It moves in two directions: Horizontal (Rows) and Vertical (Columns).

The Look: It looks like a nested list: [[row1], [row2]].


Real-World Example

Think of a Student Marksheet.

Rows: Different students (Student A, Student B).

Columns: Different subjects (Math, Science, English).

Math	Science	English
Student 1	80	85	90
Student 2	75	80	85


How to explain the "Big 5" for a 2D Array:

If we have: arr2d = np.array([[80, 85, 90], [75, 80, 85]])

ndim (Dimensions): It will be 2. Because it has two axes (Height and Width).

shape: It will be (2, 3). This means 2 rows and 3 columns. (Always Rows first, then Columns).

size: It will be 6. (Total number of cells: 2 * 3 = 6).

dtype: Usually int64 or float64.

type(): Still numpy.ndarray.


Why is 2D the "King" of Data Engineering?

Almost everything you did in MySQL or MongoDB translates to a 2D array. When you load a CSV file or a SQL table into your Python code using a library like Pandas, it treats that data as a 2D structure.

If you understand 2D arrays, you understand how data is stored in 90% of the world's databases!

In [16]:
import numpy as np

arr2d = np.array([
    [80,85,90],
    [75,80,85]])

print(arr2d)
print(f"The Shape Of Array :- {arr2d.shape}")
print(f"The Size Of Array :- {arr2d.size}")
print(f"The Datatype Of An Array :- {arr2d.dtype}")
print(f"The Diamension Of An Array :- {arr2d.ndim}")

[[80 85 90]
 [75 80 85]]
The Shape Of Array :- (2, 3)
The Size Of Array :- 6
The Datatype Of An Array :- int64
The Diamension Of An Array :- 2


In [ ]:
## Practise Questions For 1D And 2D

Question 1: The Inventory (1D)

You are tracking the stock of 5 different items in a warehouse. You create this array:
stock = np.array([150, 200, 50, 0, 300])

A) What is the ndim of this array?

B) What is the shape?


Question 2: The Sales Table (2D)

You have a table showing sales for 3 different stores over 4 days.
sales = np.array([[10, 12, 11, 15], [20, 22, 21, 25], [5, 8, 7, 9]])

A) How many Rows and Columns does this array have? (Answer in shape format).

B) What is the size of this array?




Question 3: The Reshape Puzzle

You have a 1D array with 12 elements: data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

You want to turn this into a 2D Table for a report. Which of these reshape commands will WORK and which will FAIL?

data.reshape(3, 4)

data.reshape(2, 5)

data.reshape(6, 2)


In [ ]:
## now we will learrn the range and arrange function 
 so basically range function is built in function in python and 
arrange function is a function of numpy pacakge and range is slower than arrange so when we have large amount of data in array we mostly prefer 
 arrange over range

In [6]:
for i in range(10,1,-1):  ## here it will work diaply 10 to 1 in revrese order 
    print(i)

10
9
8
7
6
5
4
3
2


In [11]:
import numpy as np  ## here we have used arange function using numpy both arange and range work same 
arr1 = np.arange(5)
print(arr1)


[0 1 2 3 4]


In [ ]:
## if we want to create a metrix of 0 like if we want to create a 2d  array 4,5 with full of zeros so we have command for that
## if we want to create a metrix of 0 like if we want to create a 2d  array 4,5 with full of zeros so we have command for that
## why we use this cause as we have see that book my show app when we went to book a ticket so when they release a show they create a metrix of 0 
##then when user book a ticket then that particular space will convert to 1 so if any other user want that seat then it show that 
## kindly select another seat caue they have a logic that if seat == 1 then show that select anpother seat.

In [15]:
## if we want to create a metrix of 0 like if we want to create a 2d  array 4,5 with full of zeros so we have command for that

import numpy as np
arr2 = np.zeros((4,5))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
## if we want to create a metrix of 0 like if we want to create a 2d  array 4,5 with full of zeros so we have command for that


import numpy as np
arr2 = np.ones((4,5))
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
## let say in our 0 metriix we want to feel 1 at the 1 row second element so simply we write 

import numpy as np
arr3 = np.zeros((4,5))
print(arr3)
print()
print()
arr3[0][1] = 1

print(arr3)

## see we have a change 0 to 1 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
## now there is a function of numpy name linespace what does this do it divide in a equal parts let say we have value 0,100 and we have to divide it into 
## 5 parts so what we wll do we will use linespace 

np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.linspace(3,10).reshape(2,5,5)  ## we can convert it into an array also.

array([[[ 3.        ,  3.14285714,  3.28571429,  3.42857143,
          3.57142857],
        [ 3.71428571,  3.85714286,  4.        ,  4.14285714,
          4.28571429],
        [ 4.42857143,  4.57142857,  4.71428571,  4.85714286,
          5.        ],
        [ 5.14285714,  5.28571429,  5.42857143,  5.57142857,
          5.71428571],
        [ 5.85714286,  6.        ,  6.14285714,  6.28571429,
          6.42857143]],

       [[ 6.57142857,  6.71428571,  6.85714286,  7.        ,
          7.14285714],
        [ 7.28571429,  7.42857143,  7.57142857,  7.71428571,
          7.85714286],
        [ 8.        ,  8.14285714,  8.28571429,  8.42857143,
          8.57142857],
        [ 8.71428571,  8.85714286,  9.        ,  9.14285714,
          9.28571429],
        [ 9.42857143,  9.57142857,  9.71428571,  9.85714286,
         10.        ]]])

In [24]:
np.eye(5)  ## Generate the identity metrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
## now we will learn rand , randn, randint 

np.random.rand(4,5) # random float value between 0 and 1 (1 is exclusive)

array([[0.06047876, 0.11418146, 0.67822012, 0.92521857, 0.43935463],
       [0.06490419, 0.89330854, 0.25034423, 0.35961588, 0.32930188],
       [0.79615752, 0.72932375, 0.88662239, 0.13723636, 0.21565161],
       [0.5223879 , 0.57616195, 0.27341109, 0.28082198, 0.34432527]])

In [27]:
np.random.randn(3,5) ## Generate a SND (Standard normal distributaion ) 

array([[ 1.60596183, -0.26974355,  0.16708219,  0.10323631, -1.22941698],
       [-1.23140161,  1.32257222, -2.38440919, -0.83586731, -0.64142345],
       [-0.47727823, -0.75564216,  0.86445857, -0.39344846, -0.3523512 ]])

In [28]:
np.random.randint(3,300,30) ## here we have used randint function in randint function 3,300 are range from 3 to 300 and 30 is number of random number we want!


array([160,   3, 117,  50,  74,   5,  91,  47, 276,  60, 197, 212, 226,
        67, 297, 262,  39, 175, 226,  80,  60,  54, 154, 122, 263, 297,
       209, 192, 134, 182])

In [6]:
## Broadcasting :- The Ability to access each and every element in a array
import numpy as np
a = np.array([[2,3,4],[4,5,6],[6,7,8]])
b = np.array([4,5,6])

print(a)
print()
print()
print(b)

print(f"sum of array a and b is \n {a + b}")
print()
print(f"multiplication of array a and b is \n {a * b}")
print()
print(f"substence  of array a and b is \n {a - b}")
print()
print(f"division of array a and b is \n {a / b}")

[[2 3 4]
 [4 5 6]
 [6 7 8]]


[4 5 6]
sum of array a and b is 
 [[ 6  8 10]
 [ 8 10 12]
 [10 12 14]]

multiplication of array a and b is 
 [[ 8 15 24]
 [16 25 36]
 [24 35 48]]

substence  of array a and b is 
 [[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]

division of array a and b is 
 [[0.5        0.6        0.66666667]
 [1.         1.         1.        ]
 [1.5        1.4        1.33333333]]


In [ ]:
np.min
np.max
np.argmin
np.argmax
np.mean


In [17]:
import numpy as np
a = np.array([[2,3,4],[4,5,6],[6,7,8]])
b = np.array([4,5,6])

print(a)
print()
print()
print(b)


print(f"minimum value in array a is :- {np.min(a)}")
print(f"minimum value in array b is :- {np.min(b)}")
print(f"maximum value in array a is :- {np.max(a)}")
print(f"maximum value in array b is :- {np.max(b)}")
print(f"Index of minimum value in array a is :- {np.argmin(a)}")
print(f"Index of minimum value in array b is :- {np.argmin(b)}")
print(f"Index of maximum value in array a is :- {np.argmax(a)}")
print(f"Index of maximum value in array b is :- {np.argmax(b)}")
print(f"Mean value of array a is :- {np.mean(a)}")
print(f"Mean value of array b is :- {np.mean(b)}")


[[2 3 4]
 [4 5 6]
 [6 7 8]]


[4 5 6]
minimum value in array a is :- 2
minimum value in array b is :- 4
maximum value in array a is :- 8
maximum value in array b is :- 6
Index of minimum value in array a is :- 0
Index of minimum value in array b is :- 0
Index of maximum value in array a is :- 8
Index of maximum value in array b is :- 2
Mean value of array a is :- 5.0
Mean value of array b is :- 5.0


In [1]:
## Where function 
## Indexing and slicing 

import numpy as np
a = np.array([[2,3,4],[4,5,6],[6,7,8]])
a[np.where(a%2==0)]

array([2, 4, 4, 6, 6, 8])

In [5]:
import numpy as np
arrr = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
print(arrr[2:7])

[3, 4, 5, 6, 7]
